### ISSUE TITLE
A feature vector (300 dim) as an input getting an error

### ISSUE THREAD

**Issue by Jeriousman** [shenweichen/DeepCTR-Torch#231]
**Describe the question(问题描述)**
I have many column features in my dataframe. 2 of them are word embedding features. Each of them have 300 embedding dim and I have this as nd.array in a single column. I would like to put them all as data but I am failing. I checked your FAQ section and found
```3. How to add a long dense feature vector as a input to the model?``` but this is not really helping as I am able to put the word embedding in just like pic_vec in the example  ```model_input = {'user_id':user_id,'item_id':item_id,'pic_vec':pic_vec}```. 
Then I followed your instruction as below:

```
model = DeepFM(linear_feature_columns=linear_feature_columns, dnn_feature_columns=dnn_feature_columns,
               task='binary',
               l2_reg_embedding=1e-5, device=device)

model.compile("adagrad", "binary_crossentropy",
              metrics=["binary_crossentropy", "auc"], )
model.fit(train_model_input, train[target].values,batch_size=32,epochs=10,verbose=2,validation_split=0.0)
```

Then I get this error
```
model.fit(train_model_input, train[target].values,batch_size=32,epochs=10,verbose=2,validation_split=0.0)
Traceback (most recent call last):

  File "<ipython-input-192-08cb75172316>", line 1, in <module>
    model.fit(train_model_input, train[target].values,batch_size=32,epochs=10,verbose=2,validation_split=0.0)

  File "/home/hojun/anaconda3/envs/ai/lib/python3.6/site-packages/deepctr_torch/models/basemodel.py", line 197, in fit
    torch.from_numpy(y))

  File "/home/hojun/anaconda3/envs/ai/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 257, in __init__
    assert all(tensors[0].size(0) == tensor.size(0) for tensor in tensors), "Size mismatch between tensors"

AssertionError: Size mismatch between tensors
```
Every column (feature) has (28992,) size series in the train_model_input, but word embedding is (28992, 300). But if I am correct, this is how you want me to do in the ```3. How to add a long dense feature vector as a input to the model?```

Can you provide what should be done?

**Additional context**

**Operating environment(运行环境):**
 - python version 3.6
 - torch version 1.7.0
 - deepctr-torch version 0.2.7

**Comment by zanshuxun** [comment]
> 2 of them are word embedding features

Could you provide a sample of your input word embedding features？

**Comment by hojun0705** [comment]
Hi @zanshuxun, sorry for the delayed reply.
Here is how my final input looks.
![스크린샷, 2022-03-01 21-40-15](https://user-images.githubusercontent.com/38139484/156170819-24c13094-a6ac-4d59-9f7e-93c12deabdf6.png)
You see, card_embedding and  user_embedding. If I take one embedding out of them, it looks as below:
```
array([ 3.66804339e-02,  2.74386927e-02,  9.88905132e-02,  9.64219868e-02,
       -8.91181082e-02,  7.80300573e-02,  1.57335065e-02, -1.16644964e-01,
        9.29633230e-02,  1.52194560e-01, -7.76028112e-02, -1.64605036e-01,
       -5.34074567e-02, -8.92045721e-03, -9.14340541e-02,  4.69021276e-02,
        7.84098282e-02,  1.31673172e-01,  9.02709961e-02, -1.48261175e-01,
       -1.64388027e-02,  9.72493514e-02,  1.44246414e-01,  2.94299647e-02,
        5.48502617e-02,  1.25673076e-04, -9.68695730e-02,  5.57996966e-02,
        4.72073033e-02, -3.64854606e-03,  4.81356233e-02,  3.08770072e-02,
       -5.08083776e-02, -1.55300566e-03,  4.16692114e-03,  6.32646354e-03,
       -6.13335520e-02,  2.26711705e-02,  5.79494908e-02,  1.00273982e-01,
        1.02893405e-01, -1.02349177e-01,  1.73082143e-01, -5.15814871e-02,
        4.24499512e-02,  2.94053815e-02, -4.37961146e-02, -4.41148542e-02,
        3.40440534e-02, -1.26885306e-02, -9.60286427e-03,  2.46717669e-02,
        3.77061628e-02,  6.99022086e-03,  2.87000872e-02,  4.18294258e-02,
       -1.15017360e-02,  1.77273229e-02,  2.19997838e-02, -9.58658829e-02,
       -8.99726003e-02,  7.69449845e-02, -9.49096680e-02, -5.99772148e-02,
       -1.38617624e-02, -3.26707624e-02, -2.82728411e-02,  3.12160924e-02,
       -7.76909739e-02,  1.01942271e-01,  8.17464218e-02,  8.61816406e-02,
        1.03244357e-01,  6.01806641e-02, -1.86360672e-01, -4.74650078e-02,
        2.10096575e-02,  8.36859792e-02,  8.21940079e-02,  8.08410645e-02,
       -2.03721784e-02, -1.34521484e-01,  1.05251735e-02, -1.40730543e-02,
       -5.30293770e-02, -2.98860334e-02, -1.10036217e-01,  1.59016922e-01,
        1.10321045e-02,  7.21232081e-03,  2.60959193e-02,  6.33544922e-02,
       -1.53520368e-02, -1.09596677e-01, -1.28255203e-01, -1.99652780e-02,
        5.02658412e-02,  5.62472865e-02,  6.95122629e-02, -4.02967669e-02,
       -1.59267843e-01, -3.62413190e-02,  4.58848737e-02,  1.11130606e-02,
       -1.65473088e-03, -5.01573347e-02,  9.09084734e-03, -1.12999808e-02,
        6.77490234e-03, -6.29645437e-02, -7.61549175e-02, -4.02255580e-02,
       -1.99788418e-02, -1.32717555e-02,  3.62447090e-02, -6.46294504e-02,
        4.46811244e-02, -1.89751517e-02,  5.88677600e-02,  2.65842024e-03,
       -1.30377874e-01,  2.83745658e-02, -1.08174644e-01,  7.83555806e-02,
        2.95681413e-03, -1.07014971e-02, -8.25920105e-02, -7.32421875e-03,
        4.71394844e-02, -5.00085615e-02, -1.55714244e-01, -7.14217275e-02,
       -9.59065780e-02, -1.03081595e-02, -7.57480189e-02, -1.24782987e-03,
        2.80168317e-02,  3.36100273e-02, -1.27902562e-02,  8.64732563e-02,
        4.93342094e-02, -1.12575954e-02,  6.53754361e-03, -4.54101562e-02,
       -8.81890208e-02,  4.28059883e-02, -6.24457449e-02, -6.99734166e-02,
       -4.55966517e-02, -9.86192524e-02,  7.26318359e-02,  6.28797710e-02,
       -4.36876081e-02,  2.39325631e-02, -5.46129011e-02,  5.39822038e-03,
       -9.39771906e-03, -4.78786901e-02, -9.67568308e-02, -6.78168377e-04,
        1.55978731e-03,  4.68173549e-02,  4.53787893e-02,  1.18815102e-01,
        5.11745885e-02, -1.39261886e-01,  4.12936732e-02,  1.22612845e-02,
        2.29017474e-02, -5.39822057e-02, -1.71630859e-01, -2.48209629e-02,
       -3.78757045e-02, -5.60913086e-02, -1.27129450e-01,  3.14737968e-02,
        1.07164174e-01, -8.24924037e-02,  4.45014089e-02,  3.72314453e-03,
        6.82576513e-03, -2.28424072e-02,  1.23460554e-02,  7.50868022e-02,
        1.57029890e-02,  9.49435780e-05, -1.26051158e-01,  8.62630233e-02,
        6.83322474e-02, -2.16946080e-02,  6.85899556e-02,  3.20909284e-02,
        4.40945104e-02,  1.21527780e-02,  4.10970040e-02,  5.70644811e-02,
       -2.96766497e-02, -7.83665944e-03, -8.74701589e-02, -1.58148870e-01,
       -4.71462682e-02, -6.13064226e-03, -3.84792760e-02, -4.61154524e-03,
        2.42919922e-02,  3.51291243e-03, -1.02898493e-01,  4.09749337e-02,
       -1.11219613e-03,  1.51909720e-02, -4.07420285e-03,  4.17887382e-02,
       -2.90120449e-02,  3.78417969e-03, -1.37898758e-01,  4.10291888e-02,
        1.07259117e-01, -5.57725690e-02, -8.75040665e-02,  3.47764753e-02,
       -9.80444998e-02, -2.98394100e-03,  4.96940613e-02, -6.76006731e-03,
        1.31456167e-01, -1.20347768e-01,  2.83338763e-02,  1.74764004e-02,
       -4.32451032e-02,  1.76595058e-02,  1.08778216e-02, -5.29242605e-02,
       -5.61591238e-02, -4.68750000e-02,  6.54542744e-02,  2.01890729e-02,
       -2.22354457e-02,  7.79893668e-03,  3.28436941e-02,  1.29894679e-02,
        6.11843541e-02,  2.72013340e-02,  3.26724574e-02, -5.99772148e-02,
       -5.91091588e-02, -1.68728307e-02,  3.52647575e-03,  1.21188693e-01,
       -3.12694982e-02, -1.40245222e-02,  2.19997838e-02, -2.33289925e-03,
        1.13511831e-01,  1.04085289e-01,  1.00382484e-01, -5.34532331e-02,
        8.73311386e-02,  3.47559191e-02, -5.68712018e-02, -5.66813163e-02,
       -6.26424178e-02,  1.49502223e-02, -8.05664062e-03,  5.58607318e-02,
        1.49061419e-02,  1.04912654e-01, -3.78350168e-02,  7.88031705e-03,
       -6.05994314e-02, -2.12741420e-02, -6.44938136e-03,  7.81792551e-02,
        1.57090932e-01,  9.11119282e-02,  2.63264980e-02, -1.22450083e-01,
       -4.62171771e-02, -1.39819682e-01, -6.51041642e-02, -2.20811628e-02,
        5.27513288e-02, -7.39067942e-02,  2.93884277e-02,  6.34528250e-02,
        5.59319407e-02,  7.16349259e-02, -1.43191023e-02, -3.90116386e-02,
       -3.71636301e-02,  4.93910052e-02, -8.49702582e-03,  8.58018696e-02,
       -9.88498256e-02,  3.75908762e-02, -7.43387043e-02, -2.30746809e-03,
       -6.14895299e-02, -1.51163740e-02,  3.61328125e-02, -4.78312187e-02],
      dtype=float32)
```
Do you have any idea how I can integrate the data?

**Comment by zanshuxun** [comment]
28992 is the number of your training samples, right? I think the format of your features is OK. The error indicates the shape between your `x` and `y` is different. What about the shape of `train[target].values`?

**Comment by Jeriousman** [comment]
Somehow this time it worked out. Thank you for your advance. Maybe I set the lengths differently somehow previously as you said.
