### ISSUE TITLE
Error when running run_dien.py

### ISSUE THREAD

**Issue by erlebach** [shenweichen/DeepCTR-Torch#249]
After installation of DeepCTR via `python setup.py install`, I get the following error: 
``` python
cuda ready...
cuda:0
Train on 4 samples, validate on 0 samples, 2 steps per epoch
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "run_dien.py", line 68, in <module>
    history = model.fit(x, y, batch_size=2, epochs=10, verbose=1, validation_split=0, shuffle=False)
  File "/home/erlebach/anaconda3/envs/torch/lib/python3.8/site-packages/deepctr_torch-0.2.8-py3.8.egg/deepctr_torch/models/basemodel.py", line 245, in fit
  File "/home/erlebach/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/erlebach/anaconda3/envs/torch/lib/python3.8/site-packages/deepctr_torch-0.2.8-py3.8.egg/deepctr_torch/models/dien.py", line 92, in forward
  File "/home/erlebach/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/erlebach/anaconda3/envs/torch/lib/python3.8/site-packages/deepctr_torch-0.2.8-py3.8.egg/deepctr_torch/models/dien.py", line 220, in forward
  File "/home/erlebach/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/utils/rnn.py", line 249, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
```
Any help is appreciated.

**Comment by zanshuxun** [comment]
1. There should be exact error message at the end of the traceback text. Maybe the error message is incomplete.

2. Please provide more infomations for us to reproduce:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Operating environment:**
 - python version [e.g. 3.5, 3.6]
 - torch version [e.g. 1.6.0, 1.7.0]
 - deepctr-torch version [e.g. 0.2.7,]

**Additional context**
Add any other context about the problem here.

**Comment by erlebach** [comment]
Thanks for the reply. Here is more detail. I am running on an M1 Mac, with Python 3.8.5, with the following versions of torch libraries: 
```
torch                        1.10.0+cu113
torch-cluster                1.5.9
torch-geometric              2.0.1
torch-scatter                2.0.9
torch-sparse                 0.6.12
torch-spline-conv            1.2.1
```

Here is the full error message (note that I get no error when running `din.py'. But when running `dien.py` with the default parameters, I get the following trace: 
``` python
cuda ready...
==> basemodel, linear_feature_columns:  []
==> basemodel, dnn_feature_columns:  [SparseFeat(name='user', vocabulary_size=4, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='user', group_name='default_group'), SparseFeat(name='gender', vocabulary_size=2, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='gender', group_name='default_group'), SparseFeat(name='item_id', vocabulary_size=4, embedding_dim=8, use_hash=False, dtype='int32', embedding_name='item_id', group_name='default_group'), SparseFeat(name='cate_id', vocabulary_size=3, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='cate_id', group_name='default_group'), DenseFeat(name='pay_score', dimension=1, dtype='float32'), VarLenSparseFeat(sparsefeat=SparseFeat(name='hist_item_id', vocabulary_size=4, embedding_dim=8, use_hash=False, dtype='int32', embedding_name='item_id', group_name='default_group'), maxlen=4, combiner='mean', length_name='seq_length'), VarLenSparseFeat(sparsefeat=SparseFeat(name='hist_cate_id', vocabulary_size=3, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='cate_id', group_name='default_group'), maxlen=4, combiner='mean', length_name='seq_length'), VarLenSparseFeat(sparsefeat=SparseFeat(name='neg_hist_item_id', vocabulary_size=4, embedding_dim=8, use_hash=False, dtype='int32', embedding_name='item_id', group_name='default_group'), maxlen=4, combiner='mean', length_name='seq_length'), VarLenSparseFeat(sparsefeat=SparseFeat(name='neg_hist_cate_id', vocabulary_size=3, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='cate_id', group_name='default_group'), maxlen=4, combiner='mean', length_name='seq_length')]

After build_input_features
==> BaseModel: self.feature_index:  OrderedDict([('user', (0, 1)), ('gender', (1, 2)), ('item_id', (2, 3)), ('cate_id', (3, 4)), ('pay_score', (4, 5)), ('hist_item_id', (5, 9)), ('seq_length', (9, 10)), ('hist_cate_id', (10, 14)), ('neg_hist_item_id', (14, 18)), ('neg_hist_cate_id', (18, 22))])
==> BaseModel: self.dnn_feature_columns:  [SparseFeat(name='user', vocabulary_size=4, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='user', group_name='default_group'), SparseFeat(name='gender', vocabulary_size=2, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='gender', group_name='default_group'), SparseFeat(name='item_id', vocabulary_size=4, embedding_dim=8, use_hash=False, dtype='int32', embedding_name='item_id', group_name='default_group'), SparseFeat(name='cate_id', vocabulary_size=3, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='cate_id', group_name='default_group'), DenseFeat(name='pay_score', dimension=1, dtype='float32'), VarLenSparseFeat(sparsefeat=SparseFeat(name='hist_item_id', vocabulary_size=4, embedding_dim=8, use_hash=False, dtype='int32', embedding_name='item_id', group_name='default_group'), maxlen=4, combiner='mean', length_name='seq_length'), VarLenSparseFeat(sparsefeat=SparseFeat(name='hist_cate_id', vocabulary_size=3, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='cate_id', group_name='default_group'), maxlen=4, combiner='mean', length_name='seq_length'), VarLenSparseFeat(sparsefeat=SparseFeat(name='neg_hist_item_id', vocabulary_size=4, embedding_dim=8, use_hash=False, dtype='int32', embedding_name='item_id', group_name='default_group'), maxlen=4, combiner='mean', length_name='seq_length'), VarLenSparseFeat(sparsefeat=SparseFeat(name='neg_hist_cate_id', vocabulary_size=3, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='cate_id', group_name='default_group'), maxlen=4, combiner='mean', length_name='seq_length')]
\==> ncreate_embedding_matrix
sparse_feature feat:  SparseFeat(name='user', vocabulary_size=4, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='user', group_name='default_group')
sparse_feature feat:  SparseFeat(name='gender', vocabulary_size=2, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='gender', group_name='default_group')
sparse_feature feat:  SparseFeat(name='item_id', vocabulary_size=4, embedding_dim=8, use_hash=False, dtype='int32', embedding_name='item_id', group_name='default_group')
sparse_feature feat:  SparseFeat(name='cate_id', vocabulary_size=3, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='cate_id', group_name='default_group')
varlen_sparse_feature feat:  VarLenSparseFeat(sparsefeat=SparseFeat(name='hist_item_id', vocabulary_size=4, embedding_dim=8, use_hash=False, dtype='int32', embedding_name='item_id', group_name='default_group'), maxlen=4, combiner='mean', length_name='seq_length')
varlen_sparse_feature feat:  VarLenSparseFeat(sparsefeat=SparseFeat(name='hist_cate_id', vocabulary_size=3, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='cate_id', group_name='default_group'), maxlen=4, combiner='mean', length_name='seq_length')
varlen_sparse_feature feat:  VarLenSparseFeat(sparsefeat=SparseFeat(name='neg_hist_item_id', vocabulary_size=4, embedding_dim=8, use_hash=False, dtype='int32', embedding_name='item_id', group_name='default_group'), maxlen=4, combiner='mean', length_name='seq_length')
varlen_sparse_feature feat:  VarLenSparseFeat(sparsefeat=SparseFeat(name='neg_hist_cate_id', vocabulary_size=3, embedding_dim=4, use_hash=False, dtype='int32', embedding_name='cate_id', group_name='default_group'), maxlen=4, combiner='mean', length_name='seq_length')

self.embedding_dict:  ModuleDict(
  (user): Embedding(4, 4)
  (gender): Embedding(2, 4)
  (item_id): Embedding(4, 8)
  (cate_id): Embedding(3, 4)
)
Traceback (most recent call last):
  File "run_dien.py", line 67, in <module>
    model = DIEN(feature_columns, behavior_feature_list,
  File "../deepctr_torch/models/dien.py", line 49, in __init__
    super(DIEN, self).__init__([], dnn_feature_columns, l2_reg_linear=0, l2_reg_embedding=l2_reg_embedding,
  File "../deepctr_torch/models/basemodel.py", line 128, in __init__
    print("self.embedding_dict['item_gender']: ", self.embedding_dict['item_gender'])
  File "/home/erlebach/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/container.py", line 313, in __getitem__
    return self._modules[key]
KeyError: 'item_gender'
```
It seems that the synthetic data is missing a field. I could try and fix it, but I find this potential omission strange since I am sure all these examples were executed prior to release. :-)

**Comment by erlebach** [comment]
Here is the solution. First, the problem only occurs when running on the GPU. Second, to fix, update torch function `.../torch/nn/utils/rnn.py`. Replace `lengths` by `lengths.cpu()` in the call to `_VF._pack_padded_sequence`. I got this information from https://github.com/pytorch/pytorch/issues/43227  .

**Comment by zanshuxun** [comment]
Yes, adding `.cpu()` works for me, too. See https://github.com/shenweichen/DeepCTR-Torch/issues/240 for more details.
