### ISSUE TITLE
index out of range error when I use trained model to predict on another data set

### ISSUE THREAD

**Issue by Bonnieliuliu** [shenweichen/DeepCTR-Torch#95]
I trained a classification model using DeepFM model, it worked well.
I load this trained model and use it to predict on another data set, error occurred. the error message is like below.

The root cause is on functional.py, caused by the following instrument, len(weight) =35, and an element in input is 35, so index out of range error occurred. How can I fix this?

```python
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
```

Error Message
Traceback (most recent call last):
  File "D:/DeepCTR-Torch/examples/run_classification_churn.py", line 134, in <module>
    pred_ans = model.predict(test_model_input, 256)
  File "D:\DeepCTR-Torch\deepctr_torch\models\basemodel.py", line 300, in predict
    y_pred = model(x).cpu().data.numpy()  # .squeeze()
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\DeepCTR-Torch\deepctr_torch\models\deepfm.py", line 73, in forward
    self.embedding_dict)
  File "D:\DeepCTR-Torch\deepctr_torch\models\basemodel.py", line 324, in input_from_feature_columns
    feat in sparse_feature_columns]
  File "D:\DeepCTR-Torch\deepctr_torch\models\basemodel.py", line 324, in <listcomp>
    feat in sparse_feature_columns]
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\nn\functional.py", line 1485, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 35 out of table with 34 rows. at C:\w\1\s\tmp_conda_3.6_171155\conda\conda-bld\pytorch_1570813991702\work\aten\src\TH/generic/THTensorEvenMoreMath.cpp:418

**Comment by Bonnieliuliu** [comment]
@chenkkkk @tangaqi @JyiHUO @Zengai

**Comment by shenweichen** [comment]
input index of prediction data is greater than the vocabulary_size of your sprase feat

**Comment by Bonnieliuliu** [comment]
Yeah, thanks! Is there any solution/suggestion to fix this?

**Comment by cycyyy** [comment]
The reason is that your training data and testing data have different feature mapping. It makes no sense if you have different feature tables. See [step 2](https://deepctr-torch.readthedocs.io/en/latest/Quick-Start.html)

**Comment by Bonnieliuliu** [comment]
> The reason is that your training data and testing data have different feature mapping. It makes no sense if you have different feature tables. See [step 2](https://deepctr-torch.readthedocs.io/en/latest/Quick-Start.html)

Thanks Yu! I found that I use a feature that vary from user to user, remove it works!
